### PR TITLE
Jhkim/refactoring test

### PR DESCRIPTION
**Pull request by jhkimnew**
@jkotalik This is the cleanup after your last feedbacks of the previous PR. I mistakenly missed this change while completing the PR.

### CODE REVIEW

**Comment by jkotalik** [comment]
@jhkimnew can you sign this https://cla2.dotnetfoundation.org/

**Comment by jkotalik** [comment]
**ping**

**Comment by jhkimnew** [comment]
@jkotalik  
Two weeks ago, I tried to sign it but I did not received the email which is supposed to complete the whole sign process. So, today again, I retried the sign processing and received this below message from the web page. I guess I need to wait for the email again.

<><><>
We are preparing a contribution license agreement for you to sign electronically. Please 
look for a mail from DocuSign in your inbox, and click the View Documents link.
<><><>

**Comment by jkotalik** [comment]
Check your spam folder? I'll look at this PR once I get the chance.

**Comment by jhkimnew** [comment]
@jkotalik  I already checked the spam folder but no mail there.

**Comment by jkotalik** [comment]
LGTM pending docusign approval. Make sure to rename the commit to something more informative before merging: Ex: "Cleans up IIS initialization testing framework"

**Pull request merged**
