### PR TITLE
WebSocketClientEXE is updated to make it more reliable.

### PR DESCRIPTION
**Pull request by jhkimnew**
@bangbingsyb I have started updating websocketclientexe to add more test coverage and make it more reliable.

### CODE REVIEW

**Comment by Tratcher** [comment]
Why are you still sending PRs to this repo? I thought everything had moved to IISIntegration.

**Comment by jhkimnew** [comment]
@jkotalik  moved only ANCM to IISIntegration, not ANCM test, and that's why I am still using this repo for updating test code.

**Comment by Tratcher** [comment]
We should also move the tests, there's no reason to keep things separate.

**Comment by jkotalik** [comment]
@jhkimnew I would like to eventually have these tests as part of our main build (in IISIntegration). We should outline the steps necessary to make this happen.

**Pull request merged**
