### PR TITLE
[don't merge] adding Request-Id for tracing and correlation purpose

### PR DESCRIPTION
**Pull request by pan-wang**
prototype for correlation

### CODE REVIEW

**Review by jhkimnew — APPROVED** [review]
Looks good

**Comment by shirhatti** [comment]
Please don't merge this yet. We're just playing around with adding a correlation id.

**Comment by muratg** [comment]
Good to merge yet?

**Comment by jkotalik** [comment]
@muratg I believe this is a WIP for now.

**Comment by jkotalik** [comment]
@pan-wang I'm closing this as it has become very stale. Let's consider adding this back to ANCM today though.

**Comment by shirhatti** [comment]
The goal was to try and implement this spec https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/FlatRequestId.md

But after speaking with @glennc offline a while ago, it's probably not the role of ANCM

**Pull request closed without merging**
