### PR TITLE
Adds AppVeyor.

### PR DESCRIPTION
**Pull request by jkotalik**

### CODE REVIEW

**Comment by Eilon** [comment]
AppVeyor working now.

**Comment by jkotalik** [comment]
@Eilon Can I get approval to merge this in?

**Review by Eilon — APPROVED** [review]
But of course.

**Comment by jkotalik** [comment]
@ryanbrandenburg note I am adding the run.ps1 changes to ANCM (part of your updating of boot strappers).

**Comment by ryanbrandenburg** [comment]
Thanks @jkotalik! I'll add ANCM to the "update all repos" list so it doesn't get missed next time.

**Pull request merged**
